insert ignore into permission (id, type) values
    ('REMOVE_RESPONDENT', 'Respondent'),
    ('ADD_RESPONDENT', 'Respondent'),
    ('ADD_OTHER_RESPONDENT', 'Respondent'),
    ('CHANGE_RESPONDENT_GEO_CURRENT', 'Respondent'),
    ('IMPORT_RESPONDENTS', 'Respondent'),
    ('ADD_RESPONDENT_NAME', 'Respondent'),
    ('EDIT_RESPONDENT_NAME', 'Respondent'),
    ('REMOVE_RESPONDENT_NAME', 'Respondent'),
    ('ADD_RESPONDENT_GEO', 'Respondent'),
    ('MOVE_RESPONDENT', 'Respondent'),
    ('ADD_RESPONDENT_CONDITION_TAG', 'Respondent'),
    ('REMOVE_RESPONDENT_CONDITION_TAG', 'Respondent'),

    ('ADD_USER', 'Study'),
    ('REMOVE_USER', 'Study'),
    ('EDIT_USER', 'Study'),
    ('EDIT_GEO', 'Study'),
    ('ADD_GEO', 'Study'),
    ('REMOVE_GEO', 'Study'),
    ('ADD_FORM', 'Study'),
    ('EDIT_FORM', 'Study'),
    ('REMOVE_FORM', 'Study'),
    ('ADD_GEO_TYPE', 'Study'),
    ('EDIT_GEO_TYPE', 'Study'),
    ('REMOVE_GEO_TYPE', 'Study'),

    ('VIEW_CONFIG', 'General'),
    ('EDIT_CONFIG', 'General'),
    ('VIEW_PERMISSIONS', 'General'),
    ('EDIT_PERMISSIONS', 'General'),
    ('VIEW_STUDIES', 'General'),
    ('ADD_STUDY', 'General'),
    ('EDIT_STUDY', 'General'),
    ('REMOVE_STUDY', 'General'),
    ('VIEW_USERS', 'General'),
    ('VIEW_DEVICES', 'General'),
    ('ADD_DEVICE', 'General'),
    ('EDIT_DEVICE', 'General'),
    ('REMOVE_DEVICE', 'General'),

    ('VIEW_REPORTS', 'Data');
