insert ignore into role_permission (`role_id`, `permission_id`, `value`) values
('surveyor', 'ADD_RESPONDENT', 1),
('surveyor', 'ADD_OTHER_RESPONDENT', 1),
('surveyor', 'EDIT_GEO', 1),
('surveyor', 'ADD_GEO', 1),
('surveyor', 'ADD_GEO_PHOTO', 1),
('surveyor', 'ADD_RESPONDENT_NAME', 1),
('surveyor', 'EDIT_RESPONDENT_NAME', 1),
('surveyor', 'REMOVE_RESPONDENT_NAME', 1),
('surveyor', 'ADD_RESPONDENT_GEO', 1),
('surveyor', 'MOVE_RESPONDENT', 1),
('surveyor', 'VIEW_RESPONDENTS', 1),
('surveyor', 'ADD_RESPONDENT_PHOTO', 1),
('surveyor', 'EDIT_RESPONDENT_PHOTO', 1),
('surveyor', 'CAN_DOWNLOAD', 1),
('surveyor', 'VIEW_CONFIG', 1);